### ISSUE TITLE
Drag and Drop doesn't work in Ubuntu for magnet links

### ISSUE THREAD

**Issue by AndrewVos** [TorrenTV/TorrenTV#62]
Is there any way to paste a magnet link in without using the drag and drop interface? A CLI maybe?

**Comment by barrabinfc** [comment]
You can use the `peerflix` module directly. If you're not familiar, this is how you install and use it.

`$ npm install -g peerflix`
`$ peerflix "magnet:?xt=urn:btih:97FCEEF8CC2228FEE253FE51A8E3D8C0C2438457&dn=slavoj+zizek+the+reality+of+the+virtual+2004+dvdrip+480p+h264&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337'" --airplay`

Or you can use `--vlc` or `--omx` to open on different players.

**Comment by umpirsky** [comment]
How to use it with TorrenTV? What about subtitles?
